import Head from "next/head";
import Image from "next/image";
import gepPic from "../public/ex86cut.png";
import exaLog from "../public/exasm.svg";
import texLog from "../public/exatex.svg";
import ProductCard from "../components/productcard";
import { useState, useEffect } from "react";
import ScrollToTop from "../components/scrolltotop";

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function Home() {
  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };

    // just trigger this so that the initial state
    // is updated as soon as the component is mounted
    // related: https://stackoverflow.com/a/63408216
    handleScroll();

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  const [hidden, setHidden] = useState(true);
  const [scrollY, setScrollY] = useState(0);
  return (
    <div className="relative" id="top">
      <Head>
        <title>ExaSm új varrógépek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/exatex.svg" />
      </Head>

      <main className="dark:bg-gray-800 bg-white relative overflow-hidden">
        <header className="h-24 sm:h-32 flex items-center z-30 w-full">
          <div className="container mx-auto px-6 flex items-center justify-between">
            <div className="relative  h-24 sm:h-32 w-full">
              <Image
                src={exaLog}
                layout="fill"
                objectFit="contain"
                alt="logo"
              />
            </div>
            <div className="flex items-center">
              <nav className="font-sen text-gray-800 dark:text-white uppercase text-lg lg:flex items-center hidden">
                <a href="#varrogep" className="py-2 px-6 hover:text-blue-600">
                  Varrógépek
                </a>
                <a href="#szabaszgep" className="py-2 px-6 hover:text-blue-600">
                  Szabászgépek
                </a>
                <a href="#vasalo" className="py-2 px-6 hover:text-blue-600">
                  Vasalóasztalok
                </a>
                <a href="#patent" className="py-2 px-6 hover:text-blue-600">
                  Patentozók
                </a>
                <a href="#presek" className="py-2 px-6 hover:text-blue-600">
                  Prések
                </a>
              </nav>
              <button className="lg:hidden flex flex-col ml-4">
                <span className="w-6 h-1 bg-gray-800 dark:bg-white mb-1"></span>
                <span className="w-6 h-1 bg-gray-800 dark:bg-white mb-1"></span>
                <span className="w-6 h-1 bg-gray-800 dark:bg-white mb-1"></span>
              </button>
            </div>
          </div>
        </header>
        <div className="bg-white dark:bg-gray-800 flex  relative items-center ">
          <div className=" mx-auto px-6 grid grid-cols-3 lg:grid-cols-5 relative py-16">
            <div className="col-span-3 lg:col-span-2 flex text-center ml-0 lg:ml-20 lg:text-left flex-col relative ">
              {/*  <span className="w-20 h-2 bg-gray-800 dark:bg-white mb-12"></span> */}
              <h1 className="font-bebas-neue uppercase text-6xl sm:text-8xl font-black flex flex-col leading-none dark:text-white text-gray-800">
                <div className="relative  h-24  w-full">
                  <Image
                    src={texLog}
                    layout="fill"
                    objectFit="contain"
                    alt="logo"
                  />
                </div>
                <span className="text-5xl sm:text-7xl">Megérkeztek!</span>
              </h1>
              <p className="text-sm sm:text-base text-gray-700 dark:text-white">
                Kimagasló minőségű és alacsony árú saját márkás gépeink .
              </p>
              <div className="flex mt-8">
                <a
                  href="mailto:exa.varrogep@gmail.com"
                  className="uppercase py-2 px-4 rounded-lg bg-blue-500 border-2 border-transparent text-white text-md mr-4 hover:bg-blue-700"
                >
                  Üzenet küldése @
                </a>
                <a
                  href="https://www.exa-sm.hu"
                  className="uppercase py-2 px-4 rounded-lg bg-transparent border-2 border-blue-500 text-blue-500 dark:text-white hover:bg-blue-500 hover:text-white text-md"
                >
                  Webshop megtekintése
                </a>
              </div>
            </div>
            <div className="hidden sm:block col-span-1 lg:col-span-3 h-96 relative">
              <Image
                src={gepPic}
                objectFit="contain"
                layout="fill"
                alt="illustration"
              />
            </div>
          </div>
        </div>
      </main>
      <div className="relative">
        <ProductCard />
        <ScrollToTop />
        <a
          className={classNames(
            scrollY > 600 ? "block" : "hidden",
            "fixed bottom-14 left-14 px-4 py-2 uppercase py-2 px-4 rounded-lg bg-transparent border-2 border-blue-500 text-blue-500 dark:text-white hover:bg-blue-500 hover:text-whitetext-xl"
          )}
          href="mailto:exa.varrogep@gmail.com"
          id="toptbn"
        >
          Üzenet küldése
        </a>
        <footer className="py-6 dark:bg-gray-800 bg-white text-center text-gray-700 dark:text-white">
          <hr className="mb-6 lg:mx-24"></hr>© 2022 <b>EXA SM KFT</b>
          <br />
          <a href="mailto:exa.varrogep@gmail.com" className="text-sm">
            Email: exa.varrogep@gmail.com
          </a>
        </footer>
      </div>
    </div>
  );
}
